In [16]:
import os
import pdfplumber
import pymupdf
import pandas as pd

In [3]:
pf = "jeevan_utsav_single_premium_cis.pdf"

In [9]:
with pdfplumber.open(pf) as pdf:
    for pageno, page in enumerate(pdf.pages):
        print(page.extract_text())

CUSTOMER INFORMATION SHEET /KNOW YOUR POLICY
This document provides key information about your policy. You are also advised to go through your Policy
Document.
Sl. Title Description in Simple Words Policy Clause
no (Please refer to applicable Policy Clause Number in next column) Number
.
1. Name of the Part A
Insurance LIC’s Jeevan Utsav Single Premium
Product and
Unique (UIN: 512N392V01)
Identification
Number (UIN)
2. Policy Number _____________________ Part A
3. Type of Non-Par, Non-Linked, Individual, Savings, Whole Life
Insurance Policy Insurance Plan
4. Basic Policy  Single Premium for Base Policy (Rs.): Schedule
details __________
(Taxes, if any, as applicable from time to time are charged
extra).
 Policy Term ------------- Schedule
Schedule
 Basic Sum Assured (Rs.) _______
 Guaranteed Addition Period ( in years): ____________
Schedule
 Survival Benefit Option chosen: ______
Schedule
 Sum Assured on Death: Higher of Basic Sum Assured or
Condition 1 A of
1.25 times of Tabular Single Premium
Part C
 Sum Assured on Maturity: Higher of Basic Sum Assured Condition 1 C of
or 1.25 times of Tabular Single Premium Part C
5. Riders opted, if <<Not Applicable (if rider is not opted)>> Schedule
any
<<Rider Name and UIN (as opted for by the policyholder)
For details of Benefits and Conditions of riders(s),
mentioned above, refer Endorsement to this policy.>>
6. Policy Coverage  Benefit payable on Death:
/ benefits On death of the Life Assured after the date of commencement Condition 1 A of
payable of risk, Death Benefit equal to “Sum Assured on Death” Part C
along with accrued Guaranteed Additions shall be payable.
However, in case of minor Life Assured, whose age at
entry is below 8 years, on death before the
commencement of Risk, the death benefit payable
shall be return of Single Premium paid excluding taxes,
1
any extra premium and rider premium(s), if any, without
interest.
 Survival benefit:
Survival Benefit in the form of Regular Income Benefit or Flexi
Condition 1 B of
Income Benefit as per the Survival Benefit Option chosen.
Part C
 Benefit payable on Maturity:
On the life assured surviving to the end of the policy term,
“Sum Assured on Maturity” along with accrued Guaranteed
Condition 1 C of
Additions shall be payable.
Part C
 Guaranteed Additions:
The Guaranteed Additions shall accrue at the rate of Rs. 40
per thousand Basic Sum Assured at the end of each policy Condition 2 of Part
year during the Guaranteed Addition Period. C
 Surrender Benefits:
The policy can be surrendered by the policyholder at any time
during the policy term. On surrender of the policy, the Condition 3 of Part
Corporation shall pay the Surrender Value higher of D
(a) Guaranteed Surrender Value and surrender value
of any accrued Guaranteed Additions; or
(b) Special Surrender Value.
 Options to Policyholders for availing benefits, if any, Condition 7 of Part
D
covered under the policy:
i) Option to take Death Benefit in instalments: This is an
option to receive Death Benefit in instalments over the
Condition 8 of Part
chosen period of 5 or 10 or 15 years instead of lump sum
D
ii) Settlement Option (for Maturity Benefit): This is an option
to receive Maturity Benefit in instalments over the chosen
period of 5 or 10 or 15 years instead of lumpsum amount.
7. Options Not Applicable
available (in
case of Linked
Insurance
Products)
8. Option available Not Applicable
(in case of
Annuity
product)
9. Exclusions Suicide Exclusion: Condition 2 of Part
(events where The provisions related to claim payment in case of death due to F
insurance suicide shall be subject to the conditions as specified herein under:
coverage is not
payable), if any. If the Life Assured (whether sane or insane) commits suicide at
any time within 12 months from the date of commencement of risk,
the Nominee or Beneficiary of the Life Assured shall be entitled to
80% of the single premium paid (excluding any taxes, extra
premium and rider premiums other than Term Assurance Rider
premium, if any) or Surrender value available as on the date of
death, whichever is higher. The nominee or beneficiary of the Life
Assured shall not be entitled to any other claim under the Policy.
2
This clause shall not be applicable in case age at entry of
the Life Assured is below 8 years.
10. Waiting/ lien Not Applicable
Period, if any
11. Grace period Not Applicable
12. Free Look 30 Days Condition 6 of Part
Period D
13. Lapse, paid-up Not Applicable
and revival of
the Policy
14. Policy Loan, if The Policy loan shall be allowed at any time after three months Condition 4 of Part
applicable from the completion of policy (i.e. 3 months from the date of D
issuance of policy) or after expiry of the free-look period,
whichever is later, and shall be subject to the terms and conditions
of the policy.
Under Option I: In the event of failure of payment of interest on the
due dates and when the outstanding loan amount along with the
interest is to exceed the Surrender Value, then the Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. The difference of Surrender Value and the loan
outstanding amount along with interest, if any, shall be payable to
the Policyholder and the policy shall be terminated.
Under Option II: In the event of failure of payment of interest on
the due dates and when the outstanding loan amount along with
the interest is to exceed the sum of Surrender Value and balance
accumulated value of Flexi Income Benefits, then Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. Any excess after adjustment shall be payable to the
Policyholder and the policy shall be terminated.
15. Claims/ Claims  Brief procedure and list of documents required Condition 4 of
Procedure including bank account details Part F
 Turn Around Time (TAT) for claims settlement:
S Service Description of Item / TAT
No. Service
1 Death Death claims settlements 15 days
Claims not requiring
Investigations
Early Death Claims 45 days
requiring investigations -
decision & payment
Settlement of Maturity On due
Survival,
Claims date
Maturity,
2
Annuity
Settlement of Survival
payments
Benefits
Auto Action Policy Payments One
by Insurer information (Survival month
3 Benefits, Maturity before
Benefits) due
date
 Link for downloading claim form :
https://licindia.in/web/guest/download-forms
For updated details, we request you to regularly check our
3
website www.licindia.in
16. Policy Servicing  Turn Around Time (TAT):
S Description of Item of Service TAT
No
1 Post Policy service requests concerning 7 days
mistakes / corrections in the policy document
2 Free look cancellation and refund from the 7 days
date of receipt of request
3 Change of Address (KYC norms to be 7 days
complied)
4 Registration / Change of Nomination, 7 days
Assignment
5 Alteration in original policy conditions (where 7 days
applicable)
6 Policy Loan 7 days
7 Issue of Duplicate Policy 7 days
8 Surrender of Policy 7 days
 Helpline/Call centre number: 91-022-68276827
 SMS LICHELP<POLICY NUMBER> to 9222492224
 WhatsApp No- 8976862090
Contact details of the Insurer:
 Please contact us at our Branch Office, the details of which
are mentioned in the Part A (First Page) of the policy
document
 Alternatively please visit https://licindia.in/branch to locate
your Brach
 Please visit https://licindia.in/web/guest/download-forms for
downloading applicable forms and list of documents required
including bank account details.
 For updated details , we request you to regularly visit our
website www.licindia.in
20. Grievances S Description of Item of Service TAT Part G
/ No
Complaints 1 Acknowledgement to complaint Immediately
2 Action on Complaint and Intimation
14 days
of decision to the complainant
3 If complaint is NOT resolved, 14 days from
communicate the details to the original date of
Policyholder of the options receipt of
including referring the complainant complaint
to Insurance Ombudsman /
Consumer Court
 Contact details of Grievance Redressal Officer of the
Insurer:
You may contact the Grievance Redressal Officer on the address
as mentioned in the Part A (First page) of the Policy Document.
4
Alternatively the details of Grievance Redressal Officers can be
found on the below link: https://licindia.in/web/guest/grievances
 Link for registering the grievance with the Insurer’s portal:
If you are a registered policy holder you can directly register
complaint/ grievance and track its status through our Customer
Portal (website) www.licindia.in. You can also contact at e-mail
id: co_complaints@licindia.com for redressal of any grievances.
Link for registering:
https://ebiz.licindia.in/D2CPM/?_ga=2.72703123.1272923387.16
77050657-120722208.1677050657#Login
 Contact details of Ombudsman:
You can also approach Insurance Ombudsman whose Address
and contact details is given in Part A (First page) of the Policy
Document.
Alternatively the details of Ombudsman can be found on the
below link:
https://cioins.co.in
022-69038800/69038812
Declaration by the Policyholder
I have read the above and confirm having noted the details.
(Signature of the Policyholder)
Place:
Date:
Note:
i. Product related documents including the Customer Information sheet are available on Corporation’s website
www.licindia.in
ii. In case of any conflict, the terms and conditions mentioned in the policy document shall prevail.
5

In [12]:
doc = pymupdf.open(pf)
for page in doc:
    print(page.get_text())

1




CUSTOMER INFORMATION SHEET /KNOW YOUR POLICY

This document provides key information about your policy. You are also advised to go through your Policy
Document.
Sl.
no
.
Title
Description in Simple Words
(Please refer to applicable Policy Clause Number in next column)
Policy Clause
Number
1.
Name
of
the
Insurance
Product
and
Unique
Identification
Number (UIN)

         LIC’s Jeevan Utsav Single Premium

           (UIN: 512N392V01)
Part  A
2.
Policy Number
    _____________________

Part  A
3.
Type
of
Insurance Policy

Non-Par, Non-Linked, Individual, Savings, Whole Life
Insurance Plan

4.
Basic
Policy
details

Single Premium for Base Policy (Rs.):
__________
(Taxes, if any, as applicable from time to time are charged
extra).


Policy Term    -------------


Basic Sum Assured (Rs.) _______


Guaranteed Addition Period ( in years): ____________


Survival Benefit Option chosen: ______


Sum Assured on Death: Higher of  Basic Sum Assured or
1.25 times of Tabular Single Premium


Sum Assured on Maturity: Higher of  Basic Sum Assured
or 1.25 times of Tabular Single Premium

Schedule


Schedule
Schedule

Schedule
Schedule
Condition 1 A of
Part C
Condition 1 C of
Part C
5.
Riders opted, if
any
<<Not Applicable (if rider is not opted)>>

<<Rider Name and UIN (as opted for by the policyholder)

For details of Benefits and Conditions of riders(s),
mentioned above, refer Endorsement to this policy.>>
Schedule

6.
Policy Coverage
/
benefits
payable


Benefit payable on Death:
On death of the Life Assured after the date of commencement
of risk, Death Benefit equal to “Sum Assured on Death”
along with accrued Guaranteed Additions shall be payable.

However, in case of minor Life Assured, whose age at
entry is below 8 years, on death before the
commencement of Risk, the death benefit payable
shall be return of Single Premium paid excluding taxes,

Condition 1 A of
Part C








2

any extra premium and rider premium(s), if any, without
interest.


Survival benefit:
Survival Benefit in the form of Regular Income Benefit or Flexi
Income Benefit as per the Survival Benefit Option chosen.

Benefit payable on Maturity:
On the life assured surviving to the end of the policy term,
“Sum Assured on Maturity” along with accrued Guaranteed
Additions shall be payable.


Guaranteed Additions:
The Guaranteed Additions shall accrue at the rate of Rs. 40
per thousand Basic Sum Assured at the end of each policy
year during the Guaranteed Addition Period.


Surrender Benefits:
The policy can be surrendered by the policyholder at any time
during the policy term. On surrender of the policy, the
Corporation shall pay the Surrender Value higher of
(a)  Guaranteed Surrender Value and surrender value
of any accrued Guaranteed Additions; or
(b) Special Surrender Value.


Options to Policyholders for availing benefits, if any,
covered under the policy:
i) Option to take Death Benefit in instalments: This is an
option to receive Death Benefit in instalments over the
chosen period of 5 or 10 or 15 years instead of lump sum
ii)  Settlement Option (for Maturity Benefit): This is an option
to receive Maturity Benefit in instalments over the chosen
period of 5 or 10 or 15 years instead of lumpsum  amount.






Condition 1 B of
Part C


Condition 1 C of
Part C



Condition 2 of Part
C



Condition 3 of Part
D





Condition 7 of Part
D


Condition 8 of Part
D

7.
Options
available
(in
case of Linked
Insurance
Products)

Not Applicable

8.
Option available
(in
case
of
Annuity
product)

Not Applicable

9.
Exclusions
(events
where
insurance
coverage is not
payable), if any.

Suicide Exclusion:
The provisions related to claim payment in case of death due to
suicide shall be subject to the conditions as specified herein under:

If the Life Assured (whether sane or insane) commits suicide at
any time within 12 months from the date of commencement of risk,
the Nominee or Beneficiary of the Life Assured shall be entitled to
80% of the single premium paid (excluding any taxes, extra
premium and rider premiums other than Term Assurance Rider
premium, if any) or Surrender value available as on the date of
death, whichever is higher. The nominee or beneficiary of the Life
Assured shall not be entitled to any other claim under the Policy.
Condition 2 of Part
F


3

This clause shall not be applicable in case age at entry of
the Life Assured is below 8 years.
10.
Waiting/
lien
Period, if any

Not Applicable

11.
Grace period

Not Applicable

12.
Free
Look
Period
30 Days

Condition 6 of Part
D
13.
Lapse, paid-up
and revival of
the Policy
Not Applicable

14.
Policy Loan,
if
applicable
The Policy loan shall be allowed at any time after three months
from the completion of policy (i.e. 3 months from the date of
issuance of policy) or after expiry of the free-look period,
whichever is later, and shall be subject to the terms and conditions
of the policy.

Under Option I: In the event of failure of payment of interest on the
due dates and when the outstanding loan amount along with the
interest is to exceed the Surrender Value, then the Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. The difference of Surrender Value and the loan
outstanding amount along with interest, if any, shall be payable to
the Policyholder and the policy shall be terminated.

Under Option II: In the event of failure of payment of interest on
the due dates and when the outstanding loan amount along with
the interest is to exceed the sum of Surrender Value and balance
accumulated value of Flexi Income Benefits, then Corporation
would be entitled to foreclose such policies with intimation to
Policyholder.  Any excess after adjustment shall be payable to the
Policyholder and the policy shall be terminated.
Condition 4 of Part
D
15.
Claims/
Claims
Procedure
 Brief procedure and list of documents required
including bank account details
 Turn Around Time (TAT) for claims settlement:

Condition 4 of
Part  F

S
No.
Service
Description of Item /
Service
TAT

1
Death
Claims
Death claims settlements
not
requiring
Investigations
15 days
Early
Death
Claims
requiring investigations -
decision & payment
45 days
2
Survival,
Maturity,
Annuity
payments
Settlement
of
Maturity
Claims
On due
date
Settlement
of
Survival
Benefits
3
Auto Action
by Insurer
Policy
Payments
information
(Survival
Benefits,
Maturity
Benefits)
One
month
before
due
date

Link for downloading claim form :
https://licindia.in/web/guest/download-forms

For updated details, we request you to regularly check our


4

website www.licindia.in

16.
Policy Servicing

Turn Around Time (TAT):


S
No
Description of Item of Service
TAT

1
Post Policy service requests concerning
mistakes / corrections in the policy document
7 days
2
Free look cancellation and refund from the
date of receipt of request
7 days
3
Change of Address (KYC norms to be
complied)
7 days
4
Registration
/
Change
of
Nomination,
Assignment
7 days
5
Alteration in original policy conditions (where
applicable)
7 days
6
Policy Loan
7 days
7
Issue of Duplicate Policy
7 days
8
Surrender of Policy
7 days
 Helpline/Call centre number: 91-022-68276827

 SMS LICHELP<POLICY NUMBER> to 9222492224

 WhatsApp No- 8976862090

Contact details of the Insurer:

 Please  contact us at our Branch Office, the details of which
are mentioned in the Part A (First Page) of the policy
document

 Alternatively please visit https://licindia.in/branch  to locate
your Brach

 Please visit https://licindia.in/web/guest/download-forms  for
downloading applicable forms and list of documents required
including bank account details.

 For updated details , we request you to regularly visit our
website www.licindia.in


20.
Grievances
/
Complaints
S
No
Description of Item of Service
TAT
Part G









1
Acknowledgement to complaint
Immediately
2
Action on Complaint and Intimation
of decision to the complainant
14 days
3
If complaint is NOT resolved,
communicate the details to the
Policyholder of the options
including referring the complainant
to Insurance Ombudsman /
Consumer Court
14
days
from
original date of
receipt
of
complaint
 Contact details of Grievance Redressal Officer of the
Insurer:
You may contact the Grievance Redressal Officer on the address
as mentioned in the Part A (First page) of the Policy Document.

5

Alternatively the details of Grievance Redressal Officers can be
found on the below link: https://licindia.in/web/guest/grievances

 Link for registering the grievance with the Insurer’s portal:
If you are a registered policy holder you can directly register
complaint/ grievance and track its status through our Customer
Portal (website) www.licindia.in. You can also contact at e-mail
id: co_complaints@licindia.com for redressal of any grievances.
Link for registering:
https://ebiz.licindia.in/D2CPM/?_ga=2.72703123.1272923387.16
77050657-120722208.1677050657#Login

Contact details of Ombudsman:
You can also approach Insurance Ombudsman whose Address
and contact details is given in Part A (First page) of the Policy
Document.
Alternatively the details of Ombudsman can be found on the
below link:
           https://cioins.co.in

        022-69038800/69038812

Declaration by the Policyholder
I have read the above and confirm having noted the details.


(Signature of the Policyholder)

Place:
Date:

Note:
i. Product related documents including the Customer Information sheet are available on Corporation’s website
www.licindia.in
ii. In case of any conflict, the terms and conditions mentioned in the policy document shall prevail.

In [42]:
page = doc[0]
tables = page.find_tables()
for table in tables:
    # print(table.to_markdown())
    df0 = table.to_pandas()

In [14]:
type(tables)

pymupdf.table.TableFinder

In [43]:
df0

,Sl.\nno\n.,Title,Description in Simple Words\n(Please refer to applicable Policy Clause Number in next column),Policy Clause\nNumber
0,1.,Name of the\nInsurance\nProduct and\nUnique\nI...,LIC’s Jeevan Utsav Single Premium\n(UIN: 512N3...,Part A
1,2.,Policy Number,_____________________,Part A
2,3.,Type of\nInsurance Policy,"Non-Par, Non-Linked, Individual, Savings, Whol...",
3,4.,Basic Policy\ndetails, Single Premium for Base Policy (Rs.):\n_____...,Schedule\nSchedule\nSchedule\nSchedule\nSchedu...
4,5.,"Riders opted, if\nany",<<Not Applicable (if rider is not opted)>>\n<<...,Schedule
5,6.,Policy Coverage\n/ benefits\npayable, Benefit payable on Death:\nOn death of the L...,Condition 1 A of\nPart C

In [44]:
page = doc[1]
tables = page.find_tables()
for table in tables:
    # print(table.to_markdown())
    df1 = table.to_pandas()

In [45]:
df1

,Col0,Col1,"any extra premium and rider premium(s), if any, without\ninterest.\n Survival benefit:\nSurvival Benefit in the form of Regular Income Benefit or Flexi\nIncome Benefit as per the Survival Benefit Option chosen.\n Benefit payable on Maturity:\nOn the life assured surviving to the end of the policy term,\n“Sum Assured on Maturity” along with accrued Guaranteed\nAdditions shall be payable.\n Guaranteed Additions:\nThe Guaranteed Additions shall accrue at the rate of Rs. 40\nper thousand Basic Sum Assured at the end of each policy\nyear during the Guaranteed Addition Period.\n Surrender Benefits:\nThe policy can be surrendered by the policyholder at any time\nduring the policy term. On surrender of the policy, the\nCorporation shall pay the Surrender Value higher of\n(a) Guaranteed Surrender Value and surrender value\nof any accrued Guaranteed Additions; or\n(b) Special Surrender Value.\n Options to Policyholders for availing benefits, if any,\ncovered under the policy:\ni) Option to take Death Benefit in instalments: This is an\noption to receive Death Benefit in instalments over the\nchosen period of 5 or 10 or 15 years instead of lump sum\nii) Settlement Option (for Maturity Benefit): This is an option\nto receive Maturity Benefit in instalments over the chosen\nperiod of 5 or 10 or 15 years instead of lumpsum amount.",Condition 1 B of\nPart C\nCondition 1 C of\nPart C\nCondition 2 of Part\nC\nCondition 3 of Part\nD\nCondition 7 of Part\nD\nCondition 8 of Part\nD
0,7.,Options\navailable (in\ncase of Linked\nInsura...,Not Applicable,
1,8.,Option available\n(in case of\nAnnuity\nproduct),Not Applicable,
2,9.,Exclusions\n(events where\ninsurance\ncoverage...,Suicide Exclusion:\nThe provisions related to ...,Condition 2 of Part\nF

In [72]:
if df1.columns[1] == 'Col1':
    header = df0.tail(1).iloc[:, 1].values[0].replace('\n', ' ').replace('/', 'and')
    txt = f"## {header} \n\n### Description\n{df0.tail(1).iloc[:, 2].values[0]}{df1.columns[2]}\n\n### Policy Clause\n{df0.tail(1).iloc[:, 3].values[0]}"
    print(txt)

## Policy Coverage and benefits payable

### Description
 Benefit payable on Death:
On death of the Life Assured after the date of commencement
of risk, Death Benefit equal to “Sum Assured on Death”
along with accrued Guaranteed Additions shall be payable.
However, in case of minor Life Assured, whose age at
entry is below 8 years, on death before the
commencement of Risk, the death benefit payable
shall be return of Single Premium paid excluding taxes,any extra premium and rider premium(s), if any, without
interest.
 Survival benefit:
Survival Benefit in the form of Regular Income Benefit or Flexi
Income Benefit as per the Survival Benefit Option chosen.
 Benefit payable on Maturity:
On the life assured surviving to the end of the policy term,
“Sum Assured on Maturity” along with accrued Guaranteed
Additions shall be payable.
 Guaranteed Additions:
The Guaranteed Additions shall accrue at the rate of Rs. 40
per thousand Basic Sum Assured at the end of each policy
year during the Guaranteed Addition Period.
 Surrender Benefits:
The policy can be surrendered by the policyholder at any time
during the policy term. On surrender of the policy, the
Corporation shall pay the Surrender Value higher of
(a) Guaranteed Surrender Value and surrender value
of any accrued Guaranteed Additions; or
(b) Special Surrender Value.
 Options to Policyholders for availing benefits, if any,
covered under the policy:
i) Option to take Death Benefit in instalments: This is an
option to receive Death Benefit in instalments over the
chosen period of 5 or 10 or 15 years instead of lump sum
ii) Settlement Option (for Maturity Benefit): This is an option
to receive Maturity Benefit in instalments over the chosen
period of 5 or 10 or 15 years instead of lumpsum amount.

### Policy Clause
Condition 1 A of
Part C

In [69]:
with open("test.md", 'w', encoding='utf-8') as f:
    f.write(txt)

In [29]:
page = doc[2]
tables = page.find_tables()
for table in tables:
    # print(table.to_markdown())
    df2 = table.to_pandas()

In [30]:
df2

,Col0,Col1,This clause shall not be applicable in case age at entry of\nthe Life Assured is below 8 years.,Col3,Col4,Col5,Col6
0,10.,"Waiting/ lien\nPeriod, if any",Not Applicable,NaN,NaN,NaN,
1,11.,Grace period,Not Applicable,NaN,NaN,NaN,
2,12.,Free Look\nPeriod,30 Days,NaN,NaN,NaN,Condition 6 of Part\nD
3,13.,"Lapse, paid-up\nand revival of\nthe Policy",Not Applicable,NaN,NaN,NaN,
4,14.,"Policy Loan, if\napplicable",The Policy loan shall be allowed at any time a...,NaN,NaN,NaN,Condition 4 of Part\nD
5,15.,Claims/ Claims\nProcedure, Brief procedure and list of documents requir...,NaN,NaN,NaN,Condition 4 of\nPart F
6,NaN,NaN,S\nNo.,Service,Description of Item /\nService,TAT,
7,NaN,NaN,1,Death\nClaims,Death claims settlements\nnot requiring\nInves...,15 days,NaN
8,NaN,NaN,NaN,NaN,Early Death Claims\nrequiring investigations -...,45 days,NaN
9,NaN,NaN,2,"Survival,\nMaturity,\nAnnuity\npayments",Settlement of Maturity\nClaims,On due\ndate,NaN
10,NaN,NaN,NaN,NaN,Settlement of Survival\nBenefits,NaN,NaN
11,NaN,NaN,3,Auto Action\nby Insurer,Policy Payments\ninformation (Survival\nBenefi...,One\nmonth\nbefore\ndue\ndate,NaN
12,NaN,NaN, Link for downloading claim form :\nhttps://l...,NaN,NaN,NaN,

In [73]:
if df2.columns[1] == 'Col1':
    header = df1.tail(1).iloc[:, 1].values[0].replace('\n', ' ').replace('/', 'and')
    t = f"## {header} \n\n### Description\n{df1.tail(1).iloc[:, 2].values[0]}{df2.columns[2]}\n\n### Policy Clause\n{df1.tail(1).iloc[:, 3].values[0]}"
    txt += "\n\n"
    txt += t
    print(txt)

## Policy Coverage and benefits payable

### Description
 Benefit payable on Death:
On death of the Life Assured after the date of commencement
of risk, Death Benefit equal to “Sum Assured on Death”
along with accrued Guaranteed Additions shall be payable.
However, in case of minor Life Assured, whose age at
entry is below 8 years, on death before the
commencement of Risk, the death benefit payable
shall be return of Single Premium paid excluding taxes,any extra premium and rider premium(s), if any, without
interest.
 Survival benefit:
Survival Benefit in the form of Regular Income Benefit or Flexi
Income Benefit as per the Survival Benefit Option chosen.
 Benefit payable on Maturity:
On the life assured surviving to the end of the policy term,
“Sum Assured on Maturity” along with accrued Guaranteed
Additions shall be payable.
 Guaranteed Additions:
The Guaranteed Additions shall accrue at the rate of Rs. 40
per thousand Basic Sum Assured at the end of each policy
year during the Guaranteed Addition Period.
 Surrender Benefits:
The policy can be surrendered by the policyholder at any time
during the policy term. On surrender of the policy, the
Corporation shall pay the Surrender Value higher of
(a) Guaranteed Surrender Value and surrender value
of any accrued Guaranteed Additions; or
(b) Special Surrender Value.
 Options to Policyholders for availing benefits, if any,
covered under the policy:
i) Option to take Death Benefit in instalments: This is an
option to receive Death Benefit in instalments over the
chosen period of 5 or 10 or 15 years instead of lump sum
ii) Settlement Option (for Maturity Benefit): This is an option
to receive Maturity Benefit in instalments over the chosen
period of 5 or 10 or 15 years instead of lumpsum amount.

### Policy Clause
Condition 1 A of
Part C

## Exclusions (events where insurance coverage is not payable), if any.

### Description
Suicide Exclusion:
The provisions related to claim payment in case of death due to
suicide shall be subject to the conditions as specified herein under:
If the Life Assured (whether sane or insane) commits suicide at
any time within 12 months from the date of commencement of risk,
the Nominee or Beneficiary of the Life Assured shall be entitled to
80% of the single premium paid (excluding any taxes, extra
premium and rider premiums other than Term Assurance Rider
premium, if any) or Surrender value available as on the date of
death, whichever is higher. The nominee or beneficiary of the Life
Assured shall not be entitled to any other claim under the Policy.This clause shall not be applicable in case age at entry of
the Life Assured is below 8 years.

### Policy Clause
Condition 2 of Part
F

In [77]:
# page = doc[2]
# tables = page.find_tables()
# for table in tables:
#     print(table.to_markdown(clean=False))
#     # df0 = table.to_pandas()

In [108]:
df2

,Col0,Col1,This clause shall not be applicable in case age at entry of\nthe Life Assured is below 8 years.,Col3,Col4,Col5,Col6
0,10.,"Waiting/ lien\nPeriod, if any",Not Applicable,NaN,NaN,NaN,
1,11.,Grace period,Not Applicable,NaN,NaN,NaN,
2,12.,Free Look\nPeriod,30 Days,NaN,NaN,NaN,Condition 6 of Part\nD
3,13.,"Lapse, paid-up\nand revival of\nthe Policy",Not Applicable,NaN,NaN,NaN,
4,14.,"Policy Loan, if\napplicable",The Policy loan shall be allowed at any time a...,NaN,NaN,NaN,Condition 4 of Part\nD
5,15.,Claims/ Claims\nProcedure, Brief procedure and list of documents requir...,NaN,NaN,NaN,Condition 4 of\nPart F
6,NaN,NaN,S\nNo.,Service,Description of Item /\nService,TAT,
7,NaN,NaN,1,Death\nClaims,Death claims settlements\nnot requiring\nInves...,15 days,NaN
8,NaN,NaN,NaN,NaN,Early Death Claims\nrequiring investigations -...,45 days,NaN
9,NaN,NaN,2,"Survival,\nMaturity,\nAnnuity\npayments",Settlement of Maturity\nClaims,On due\ndate,NaN
10,NaN,NaN,NaN,NaN,Settlement of Survival\nBenefits,NaN,NaN
11,NaN,NaN,3,Auto Action\nby Insurer,Policy Payments\ninformation (Survival\nBenefi...,One\nmonth\nbefore\ndue\ndate,NaN
12,NaN,NaN, Link for downloading claim form :\nhttps://l...,NaN,NaN,NaN,

In [154]:
for idx, row in df2.iterrows():
    try:
        if pd.isna(row.values[1]):
            break
        header = row.values[1].replace('\n', ' ').replace('/', 'and')
        description = row.values[2]
        
        if 'claim' in row.values[1].lower():
            desc_fields = claim_func(df2, idx + 1)
            description += "\n"
            for f, d in desc_fields.items():
                description += f"{f}: {d}\n"
        header = row.values[1].replace('\n', ' ').replace('/', 'and')
        # t = f"## {header}\n\n ### Description\n{row.values[2]}\n\n### Policy Clause\n{row.values[6]}"
        t = f"## {header}\n\n ### Description\n{description}\n\n### Policy Clause\n{row.values[6]}"
        txt += '\n\n'
        txt += t
        print(txt)
    except Exception as e:
        print(f"\n\n\n{idx}: {row.index}{row.values[1]}")
        print(e)

## Policy Coverage and benefits payable

### Description
 Benefit payable on Death:
On death of the Life Assured after the date of commencement
of risk, Death Benefit equal to “Sum Assured on Death”
along with accrued Guaranteed Additions shall be payable.
However, in case of minor Life Assured, whose age at
entry is below 8 years, on death before the
commencement of Risk, the death benefit payable
shall be return of Single Premium paid excluding taxes,any extra premium and rider premium(s), if any, without
interest.
 Survival benefit:
Survival Benefit in the form of Regular Income Benefit or Flexi
Income Benefit as per the Survival Benefit Option chosen.
 Benefit payable on Maturity:
On the life assured surviving to the end of the policy term,
“Sum Assured on Maturity” along with accrued Guaranteed
Additions shall be payable.
 Guaranteed Additions:
The Guaranteed Additions shall accrue at the rate of Rs. 40
per thousand Basic Sum Assured at the end of each policy
year during the Guaranteed Addition Period.
 Surrender Benefits:
The policy can be surrendered by the policyholder at any time
during the policy term. On surrender of the policy, the
Corporation shall pay the Surrender Value higher of
(a) Guaranteed Surrender Value and surrender value
of any accrued Guaranteed Additions; or
(b) Special Surrender Value.
 Options to Policyholders for availing benefits, if any,
covered under the policy:
i) Option to take Death Benefit in instalments: This is an
option to receive Death Benefit in instalments over the
chosen period of 5 or 10 or 15 years instead of lump sum
ii) Settlement Option (for Maturity Benefit): This is an option
to receive Maturity Benefit in instalments over the chosen
period of 5 or 10 or 15 years instead of lumpsum amount.

### Policy Clause
Condition 1 A of
Part C

## Exclusions (events where insurance coverage is not payable), if any.

### Description
Suicide Exclusion:
The provisions related to claim payment in case of death due to
suicide shall be subject to the conditions as specified herein under:
If the Life Assured (whether sane or insane) commits suicide at
any time within 12 months from the date of commencement of risk,
the Nominee or Beneficiary of the Life Assured shall be entitled to
80% of the single premium paid (excluding any taxes, extra
premium and rider premiums other than Term Assurance Rider
premium, if any) or Surrender value available as on the date of
death, whichever is higher. The nominee or beneficiary of the Life
Assured shall not be entitled to any other claim under the Policy.This clause shall not be applicable in case age at entry of
the Life Assured is below 8 years.

### Policy Clause
Condition 2 of Part
F

## Waitingand lien Period, if any

 ### Description
Not Applicable

### Policy Clause


## Grace period

 ### Description
Not Applicable

### Policy Clause


## Free Look Period

 ### Description
30 Days

### Policy Clause
Condition 6 of Part
D

## Lapse, paid-up and revival of the Policy

 ### Description
Not Applicable

### Policy Clause


## Policy Loan, if applicable

 ### Description
The Policy loan shall be allowed at any time after three months
from the completion of policy (i.e. 3 months from the date of
issuance of policy) or after expiry of the free-look period,
whichever is later, and shall be subject to the terms and conditions
of the policy.
Under Option I: In the event of failure of payment of interest on the
due dates and when the outstanding loan amount along with the
interest is to exceed the Surrender Value, then the Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. The difference of Surrender Value and the loan
outstanding amount along with interest, if any, shall be payable to
the Policyholder and the policy shall be terminated.
Under Option II: In the event of failure of payment of interest on
the due dates and when the outstanding loan amount along with
the interest is to exceed the sum of Surrender Value and balance
accumulated value of Flexi Income Benefits, then Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. Any excess after adjustment shall be payable to the
Policyholder and the policy shall be terminated.

### Policy Clause
Condition 4 of Part
D

## Waitingand lien Period, if any

 ### Description
Not Applicable

### Policy Clause


## Grace period

 ### Description
Not Applicable

### Policy Clause


## Free Look Period

 ### Description
30 Days

### Policy Clause
Condition 6 of Part
D

## Lapse, paid-up and revival of the Policy

 ### Description
Not Applicable

### Policy Clause


## Policy Loan, if applicable

 ### Description
The Policy loan shall be allowed at any time after three months
from the completion of policy (i.e. 3 months from the date of
issuance of policy) or after expiry of the free-look period,
whichever is later, and shall be subject to the terms and conditions
of the policy.
Under Option I: In the event of failure of payment of interest on the
due dates and when the outstanding loan amount along with the
interest is to exceed the Surrender Value, then the Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. The difference of Surrender Value and the loan
outstanding amount along with interest, if any, shall be payable to
the Policyholder and the policy shall be terminated.
Under Option II: In the event of failure of payment of interest on
the due dates and when the outstanding loan amount along with
the interest is to exceed the sum of Surrender Value and balance
accumulated value of Flexi Income Benefits, then Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. Any excess after adjustment shall be payable to the
Policyholder and the policy shall be terminated.

### Policy Clause
Condition 4 of Part
D

## Waitingand lien Period, if any

 ### Description
Not Applicable

### Policy Clause


## Grace period

 ### Description
Not Applicable

### Policy Clause


## Free Look Period

 ### Description
30 Days

### Policy Clause
Condition 6 of Part
D

## Lapse, paid-up and revival of the Policy

 ### Description
Not Applicable

### Policy Clause


## Policy Loan, if applicable

 ### Description
The Policy loan shall be allowed at any time after three months
from the completion of policy (i.e. 3 months from the date of
issuance of policy) or after expiry of the free-look period,
whichever is later, and shall be subject to the terms and conditions
of the policy.
Under Option I: In the event of failure of payment of interest on the
due dates and when the outstanding loan amount along with the
interest is to exceed the Surrender Value, then the Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. The difference of Surrender Value and the loan
outstanding amount along with interest, if any, shall be payable to
the Policyholder and the policy shall be terminated.
Under Option II: In the event of failure of payment of interest on
the due dates and when the outstanding loan amount along with
the interest is to exceed the sum of Surrender Value and balance
accumulated value of Flexi Income Benefits, then Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. Any excess after adjustment shall be payable to the
Policyholder and the policy shall be terminated.

### Policy Clause
Condition 4 of Part
D

## Waitingand lien Period, if any

 ### Description
Not Applicable

### Policy Clause


## Grace period

 ### Description
Not Applicable

### Policy Clause


## Free Look Period

 ### Description
30 Days

### Policy Clause
Condition 6 of Part
D

## Lapse, paid-up and revival of the Policy

 ### Description
Not Applicable

### Policy Clause


## Policy Loan, if applicable

 ### Description
The Policy loan shall be allowed at any time after three months
from the completion of policy (i.e. 3 months from the date of
issuance of policy) or after expiry of the free-look period,
whichever is later, and shall be subject to the terms and conditions
of the policy.
Under Option I: In the event of failure of payment of interest on the
due dates and when the outstanding loan amount along with the
interest is to exceed the Surrender Value, then the Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. The difference of Surrender Value and the loan
outstanding amount along with interest, if any, shall be payable to
the Policyholder and the policy shall be terminated.
Under Option II: In the event of failure of payment of interest on
the due dates and when the outstanding loan amount along with
the interest is to exceed the sum of Surrender Value and balance
accumulated value of Flexi Income Benefits, then Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. Any excess after adjustment shall be payable to the
Policyholder and the policy shall be terminated.

### Policy Clause
Condition 4 of Part
D

## Waitingand lien Period, if any

 ### Description
Not Applicable

### Policy Clause


## Grace period

 ### Description
Not Applicable

### Policy Clause


## Free Look Period

 ### Description
30 Days

### Policy Clause
Condition 6 of Part
D

## Lapse, paid-up and revival of the Policy

 ### Description
Not Applicable

### Policy Clause


## Policy Loan, if applicable

 ### Description
The Policy loan shall be allowed at any time after three months
from the completion of policy (i.e. 3 months from the date of
issuance of policy) or after expiry of the free-look period,
whichever is later, and shall be subject to the terms and conditions
of the policy.
Under Option I: In the event of failure of payment of interest on the
due dates and when the outstanding loan amount along with the
interest is to exceed the Surrender Value, then the Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. The difference of Surrender Value and the loan
outstanding amount along with interest, if any, shall be payable to
the Policyholder and the policy shall be terminated.
Under Option II: In the event of failure of payment of interest on
the due dates and when the outstanding loan amount along with
the interest is to exceed the sum of Surrender Value and balance
accumulated value of Flexi Income Benefits, then Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. Any excess after adjustment shall be payable to the
Policyholder and the policy shall be terminated.

### Policy Clause
Condition 4 of Part
D

## Claimsand Claims Procedure

 ### Description
 Brief procedure and list of documents required
including bank account details
 Turn Around Time (TAT) for claims settlement:

### Policy Clause
Condition 4 of
Part F

## Waitingand lien Period, if any

 ### Description
Not Applicable

### Policy Clause


## Grace period

 ### Description
Not Applicable

### Policy Clause


## Free Look Period

 ### Description
30 Days

### Policy Clause
Condition 6 of Part
D

## Lapse, paid-up and revival of the Policy

 ### Description
Not Applicable

### Policy Clause


## Policy Loan, if applicable

 ### Description
The Policy loan shall be allowed at any time after three months
from the completion of policy (i.e. 3 months from the date of
issuance of policy) or after expiry of the free-look period,
whichever is later, and shall be subject to the terms and conditions
of the policy.
Under Option I: In the event of failure of payment of interest on the
due dates and when the outstanding loan amount along with the
interest is to exceed the Surrender Value, then the Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. The difference of Surrender Value and the loan
outstanding amount along with interest, if any, shall be payable to
the Policyholder and the policy shall be terminated.
Under Option II: In the event of failure of payment of interest on
the due dates and when the outstanding loan amount along with
the interest is to exceed the sum of Surrender Value and balance
accumulated value of Flexi Income Benefits, then Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. Any excess after adjustment shall be payable to the
Policyholder and the policy shall be terminated.

### Policy Clause
Condition 4 of Part
D

## Claimsand Claims Procedure

 ### Description
 Brief procedure and list of documents required
including bank account details
 Turn Around Time (TAT) for claims settlement:

### Policy Clause
Condition 4 of
Part F

## Waitingand lien Period, if any

 ### Description
Not Applicable

### Policy Clause


## Grace period

 ### Description
Not Applicable

### Policy Clause


## Free Look Period

 ### Description
30 Days

### Policy Clause
Condition 6 of Part
D

## Lapse, paid-up and revival of the Policy

 ### Description
Not Applicable

### Policy Clause


## Policy Loan, if applicable

 ### Description
The Policy loan shall be allowed at any time after three months
from the completion of policy (i.e. 3 months from the date of
issuance of policy) or after expiry of the free-look period,
whichever is later, and shall be subject to the terms and conditions
of the policy.
Under Option I: In the event of failure of payment of interest on the
due dates and when the outstanding loan amount along with the
interest is to exceed the Surrender Value, then the Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. The difference of Surrender Value and the loan
outstanding amount along with interest, if any, shall be payable to
the Policyholder and the policy shall be terminated.
Under Option II: In the event of failure of payment of interest on
the due dates and when the outstanding loan amount along with
the interest is to exceed the sum of Surrender Value and balance
accumulated value of Flexi Income Benefits, then Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. Any excess after adjustment shall be payable to the
Policyholder and the policy shall be terminated.

### Policy Clause
Condition 4 of Part
D

## Claimsand Claims Procedure

 ### Description
 Brief procedure and list of documents required
including bank account details
 Turn Around Time (TAT) for claims settlement:

### Policy Clause
Condition 4 of
Part F

## Waitingand lien Period, if any

 ### Description
Not Applicable

### Policy Clause


## Grace period

 ### Description
Not Applicable

### Policy Clause


## Free Look Period

 ### Description
30 Days

### Policy Clause
Condition 6 of Part
D

## Lapse, paid-up and revival of the Policy

 ### Description
Not Applicable

### Policy Clause


## Policy Loan, if applicable

 ### Description
The Policy loan shall be allowed at any time after three months
from the completion of policy (i.e. 3 months from the date of
issuance of policy) or after expiry of the free-look period,
whichever is later, and shall be subject to the terms and conditions
of the policy.
Under Option I: In the event of failure of payment of interest on the
due dates and when the outstanding loan amount along with the
interest is to exceed the Surrender Value, then the Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. The difference of Surrender Value and the loan
outstanding amount along with interest, if any, shall be payable to
the Policyholder and the policy shall be terminated.
Under Option II: In the event of failure of payment of interest on
the due dates and when the outstanding loan amount along with
the interest is to exceed the sum of Surrender Value and balance
accumulated value of Flexi Income Benefits, then Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. Any excess after adjustment shall be payable to the
Policyholder and the policy shall be terminated.

### Policy Clause
Condition 4 of Part
D

## Claimsand Claims Procedure

 ### Description
 Brief procedure and list of documents required
including bank account details
 Turn Around Time (TAT) for claims settlement:

### Policy Clause
Condition 4 of
Part F

## Waitingand lien Period, if any

 ### Description
Not Applicable

### Policy Clause


## Grace period

 ### Description
Not Applicable

### Policy Clause


## Free Look Period

 ### Description
30 Days

### Policy Clause
Condition 6 of Part
D

## Lapse, paid-up and revival of the Policy

 ### Description
Not Applicable

### Policy Clause


## Policy Loan, if applicable

 ### Description
The Policy loan shall be allowed at any time after three months
from the completion of policy (i.e. 3 months from the date of
issuance of policy) or after expiry of the free-look period,
whichever is later, and shall be subject to the terms and conditions
of the policy.
Under Option I: In the event of failure of payment of interest on the
due dates and when the outstanding loan amount along with the
interest is to exceed the Surrender Value, then the Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. The difference of Surrender Value and the loan
outstanding amount along with interest, if any, shall be payable to
the Policyholder and the policy shall be terminated.
Under Option II: In the event of failure of payment of interest on
the due dates and when the outstanding loan amount along with
the interest is to exceed the sum of Surrender Value and balance
accumulated value of Flexi Income Benefits, then Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. Any excess after adjustment shall be payable to the
Policyholder and the policy shall be terminated.

### Policy Clause
Condition 4 of Part
D

## Claimsand Claims Procedure

 ### Description
 Brief procedure and list of documents required
including bank account details
 Turn Around Time (TAT) for claims settlement:

### Policy Clause
Condition 4 of
Part F

## Waitingand lien Period, if any

 ### Description
Not Applicable

### Policy Clause


## Grace period

 ### Description
Not Applicable

### Policy Clause


## Free Look Period

 ### Description
30 Days

### Policy Clause
Condition 6 of Part
D

## Lapse, paid-up and revival of the Policy

 ### Description
Not Applicable

### Policy Clause


## Policy Loan, if applicable

 ### Description
The Policy loan shall be allowed at any time after three months
from the completion of policy (i.e. 3 months from the date of
issuance of policy) or after expiry of the free-look period,
whichever is later, and shall be subject to the terms and conditions
of the policy.
Under Option I: In the event of failure of payment of interest on the
due dates and when the outstanding loan amount along with the
interest is to exceed the Surrender Value, then the Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. The difference of Surrender Value and the loan
outstanding amount along with interest, if any, shall be payable to
the Policyholder and the policy shall be terminated.
Under Option II: In the event of failure of payment of interest on
the due dates and when the outstanding loan amount along with
the interest is to exceed the sum of Surrender Value and balance
accumulated value of Flexi Income Benefits, then Corporation
would be entitled to foreclose such policies with intimation to
Policyholder. Any excess after adjustment shall be payable to the
Policyholder and the policy shall be terminated.

### Policy Clause
Condition 4 of Part
D

## Claimsand Claims Procedure

 ### Description
 Brief procedure and list of documents required
including bank account details
 Turn Around Time (TAT) for claims settlement:

### Policy Clause
Condition 4 of
Part F

## Waitingand lien Period, if any

 ### Description
Not Applicable

### Policy Clause

## Policy Coverage and benefits payable

### Description
 Benefit payable on Death:

In [153]:
# claim = df2.loc[6:].reset_index()
# claim

In [152]:
def claim_func(df, idx):

    claim = df.loc[idx:].reset_index()
    field_map = {}
    for idx, row in claim.iterrows():
        if idx == 0:
            fields = list(row.values[3:7])
            desc = ["", "", "", "", "", ""]
            field_map = dict(zip(fields, desc))
            continue
    
        fields = list(field_map.keys())
        
        field_map[fields[0]] = field_map[fields[0]] + "" if pd.isna(row.values[3]) else row.values[3]
        field_map[fields[1]] = field_map[fields[1]] + "" if pd.isna(row.values[4]) else row.values[4]
        field_map[fields[2]] = field_map[fields[0]] + "" if pd.isna(row.values[5]) else row.values[5]
        field_map[fields[3]] = field_map[fields[0]] + "" if pd.isna(row.values[6]) else row.values[6]
    
    # print(field_map)
    return field_map

In [ ]:
# func: continuation of text
# func:

In [155]:
with open("test1.md", 'w', encoding='utf-8') as f:
    f.write(txt)

In [156]:
doc = pymupdf.open(pf)
page = doc[4]
tables = page.