In [126]:
import pymupdf
import pandas as pd

In [127]:
sf = "jeevan_utsav_cis.pdf"

In [128]:
dfs = []
pages = pymupdf.open(sf)

for page in pages:
    tables = page.find_tables()
    for table in tables:
        df = table.to_pandas()
        dfs.append(df)

In [129]:
# def table_cont(df0, df1):
#         header = ""
#         if df1.columns[1] == 'Col1':
#             if not pd.isna( df0.tail(1).iloc[:, 1].values[0]):
#                 header += df0.tail(1).iloc[:, 1].values[0].replace('\n', ' ').replace('/', 'and')
#         txt = f"## {header} \n\n### Description\n{df0.tail(1).iloc[:, 2].values[0]}{df1.columns[2]}\n\n### Policy Clause\n{df0.tail(1).iloc[:, 3].values[0]}"
#         return txt
#     # print(txt)

In [130]:
# def table_cont(df0, df1, idx):
#     header = ""
#     if not pd.isna( df0.tail(1).iloc[:, idx].values[0]):
#         header += df0.tail(1).iloc[:, idx].values[0].replace('\n', ' ').replace('/', 'and')
#         txt = f"## {header} \n\n### Description\n{df0.tail(1).iloc[:, 2].values[0]}{df1.columns[2]}\n\n### Policy Clause\n{df0.tail(1).iloc[:, 3].values[0]}"
#     return txt
#     # print(txt)

In [131]:
dfs[0]

,Sl.\nNo.,Title,Description in Simple Words\n(Please refer to applicable Policy Clause Number in\nnext column),Policy\nClause\nNumber
0,1.,Name of the Insurance\nProduct\nand Unique\nId...,LIC’s Jeevan Utsav\n(UIN: 512N363V02),Part A
1,2,Policy Number,_____________________,Part A
2,3,Type of Insurance\nPolicy,"Non-Par, Non-Linked, Individual, Savings, Whol...",Part B -\nDefinitions
3,4,Basic Policy details, Instalment Premium (Rs):\n__________\n(Taxes...,Schedule\nSchedule\nSchedule\nSchedule\nCondit...
4,5,"Riders opted, if any",<<Not Applicable (if rider is not opted)>>\n<<...,Schedule
5,6,Policy Coverage /\nbenefits payable, Benefit payable on Death:\nOn death of the L...,Condition\n1.A of Part\nC

In [132]:
dfs[0].iloc[5, 2]

'\uf0b7 Benefit payable on Death:\nOn death of the Life Assured after the date of\ncommencement of risk, Death Benefit equal to\n“Sum Assured on Death” along with accrued\nGuaranteed Additions shall be payable,'

In [133]:
dfs[1]

,Col0,Col1,"provided the policy is in-force.\nThis Death Benefit shall not be less than 105%\nof total premiums paid upto the date of death.\n Survival Benefit:\nSurvival Benefits in form of Regular Income\nBenefit or Flexi Income Benefit as per the option\nchosen\n.\n Guaranteed Additions:\nUnder an inforce policy, the Guaranteed\nAdditions shall accrue at the rate of Rs. 40 per\nthousand Basic Sum Assured at the end of each\npolicy year during the Premium Paying Term.\nThere shall be no further accrual of Guaranteed\nAdditions after Premium Paying Term.\n Surrender Benefits:\nThe policy can be surrendered by the\npolicyholder after completion of first policy year\nprovided one full year’s premium(s) has been\npaid. However, the policy shall acquire\nGuaranteed Surrender Value on payment of\natleast two full years’ premiums and Special\nSurrender Value after completion of first policy\nyear provided one full year’s premium(s) has\nbeen paid. On surrender of an in-force or paid-\nup policy, the Corporation shall pay the\nSurrender Value equal to higher of Guaranteed\nSurrender Value and Special Surrender Value.\n Options to Policyholders for availing\nbenefits, if any, covered under the policy:\ni) Option to take Death Benefit in instalments:\nThis is an option to receive Death Benefit in\ninstalments over the chosen period of 5 or 10\nor 15 years instead of lump sum amount\nunder an in-force as well as paid-up policy.",Condition\n1.B of Part\nC\nCondition 2\nof Part C\nCondition 4\nof Part D\nCondition 8\nof Part D
0,7,Options available (in\ncase of Linked\nInsuran...,Not Applicable,
1,8,Option available (in\ncase of Annuity\nproduct),Not Applicable,

In [134]:
# assert dfs[1].columns[2] == df1_trans.iloc[0,2]

In [135]:
df1_trans = dfs[1].T.reset_index().T.reset_index(drop=True)
df1_trans

,0,1,2,3
0,Col0,Col1,provided the policy is in-force.\nThis Death B...,Condition\n1.B of Part\nC\nCondition 2\nof Par...
1,7,Options available (in\ncase of Linked\nInsuran...,Not Applicable,
2,8,Option available (in\ncase of Annuity\nproduct),Not Applicable,

In [136]:
dfs[2]

,9,"Exclusions (events\nwhere insurance\ncoverage is not\npayable), if any.",Suicide Exclusion: The provisions related to claim\npayment in case of death due to suicide shall be\nsubject to the conditions as specified in Condition 2\nof Part F of Policy document:\nThis clause shall not be applicable for a policy\nlapsed without acquiring paid up value and nothing\nshall be payable under such policy.\nThe relaxation mentioned under Non-forfeiture\nprovisions shall not be applicable in case of death\ndue to suicide.,Col3,Col4,Col5,Col6,Condition 2\nof Part F
0,10,"Waiting/ lien Period, if\nany",Not Applicable,NaN,NaN,NaN,NaN,
1,11,Grace period," 30 Days for Yearly, Half-yearly, Quarterly m...",NaN,NaN,NaN,NaN,Condition 6\nof Part C
2,12,Free Look Period,30 Days,NaN,NaN,NaN,NaN,Condition 7\nof Part D
3,13,"Lapse, paid-up and\nrevival of the Policy", Lapse: Lapse is the status of the policy whe...,NaN,NaN,NaN,NaN,Part B-\nDefinitions\nCondition 2\nof Part D\n...
4,14,"Policy Loan, if\napplicable",Loan can be availed after completion of first ...,NaN,NaN,NaN,NaN,Condition 5\nof Part D
5,15,Claims/ Claims\nProcedure, Brief procedure and list of documents\nrequi...,NaN,NaN,NaN,NaN,Condition 4\nof Part F
6,NaN,NaN,NaN,S\nNo,Service,Description of Item /\nService,TAT,NaN
7,NaN,NaN,NaN,1,Death\nClaims,Death claims\nsettlements not\nrequiring\nInve...,15 days,NaN

In [137]:
dfs[3]

,Col0,Col1,"Early Death Claims 45 days\nrequiring\ninvestigations -\ndecision & payment\nSettlement of Maturity\nSurvival, Claims\nMaturity, Settlement of Survival\nOn due\n2 Annuity Benefits\ndate\npayment\nAnnuity\ns\npayments/Pension\nPayments\nAuto Policy Payments One\nAction information(Survival month\n3\nby Benefits, Maturity before\nInsurer Benefits) due date\n Link for downloading claim form :\nhttps://licindia.in/web/guest/download-forms\nFor updated details, we request you to regularly\ncheck our website www.licindia.in",Col3,Col4,Early Death Claims\nrequiring\ninvestigations -\ndecision & payment,45 days,Col7
0,NaN,NaN,NaN,2,"Survival,\nMaturity,\nAnnuity\npayment\ns",Settlement of Maturity\nClaims,On due\ndate,
1,NaN,NaN,NaN,NaN,NaN,Settlement of Survival\nBenefits,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,Annuity\npayments/Pension\nPayments,NaN,NaN
3,NaN,NaN,NaN,3,Auto\nAction\nby\nInsurer,Policy Payments\ninformation(Survival\nBenefit...,One\nmonth\nbefore\ndue date,
4,16,Policy Servicing, Turn Around Time (TAT):\nS Description of It...,NaN,NaN,NaN,NaN,

In [138]:
df3_trans = dfs[3].T.reset_index().T.reset_index(drop=True)
df3_trans

,0,1,2,3,4,5,6,7
0,Col0,Col1,Early Death Claims 45 days\nrequiring\ninvesti...,Col3,Col4,Early Death Claims\nrequiring\ninvestigations ...,45 days,Col7
1,NaN,NaN,NaN,2,"Survival,\nMaturity,\nAnnuity\npayment\ns",Settlement of Maturity\nClaims,On due\ndate,
2,NaN,NaN,NaN,NaN,NaN,Settlement of Survival\nBenefits,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,Annuity\npayments/Pension\nPayments,NaN,NaN
4,NaN,NaN,NaN,3,Auto\nAction\nby\nInsurer,Policy Payments\ninformation(Survival\nBenefit...,One\nmonth\nbefore\ndue date,
5,16,Policy Servicing, Turn Around Time (TAT):\nS Description of It...,NaN,NaN,NaN,NaN,

In [139]:
df4_trans = dfs[4].T.reset_index().T.reset_index(drop=True)
df4_trans

,0,1,2
0,S\nNo,Description of Item of Service,TAT
1,1,Post Policy service requests\nconcerning mista...,7 days
2,2,Free look cancellation and refund from\nthe da...,7 days
3,3,Change of Address (KYC norms to be\ncomplied),7 days
4,4,"Registration / Change of Nomination,\nAssignment",7 days
5,5,Alteration in original policy conditions\n(whe...,7 days
6,6,Policy Loan,7 days
7,7,Decision on Policy revival after receipt\nof a...,7 days
8,8,Issue of Premium Payment certificates\n(PPC),7 days
9,9,Issue of Duplicate Policy,7 days
10,10,Premium due intimation,One\nmonth\nbefore\ndue date
11,11,Surrender or Partial withdrawal of\nPolicy,7 days

In [140]:
df5_trans = dfs[5].T.reset_index().T.reset_index(drop=True)
df5_trans

,0,1,2,3
0,Col0,Col1, WhatsApp No- 8976862090\nContact details of ...,Col3
1,17,Grievances\n/Com plaints,S Description of Item of Service TAT\nNo\n1 Ac...,Part G

In [141]:
df6_trans = dfs[6].T.reset_index().T.reset_index(drop=True)
df6_trans

,0,1,2
0,S\nNo,Description of Item of Service,TAT
1,1,Acknowledgement to complaint,Immediately
2,2,Action on Complaint and\nIntimation of decisio...,14 days
3,3,"If complaint is NOT resolved,\ncommunicate the...",14 days from\noriginal date\nof receipt of\nco...

In [142]:
len(dfs)

8

In [143]:
df7_trans = dfs[7].T.reset_index().T.reset_index(drop=True)
df7_trans

      0     1                                                  2     3
0  Col0  Col1  www.licindia.in. You can also contact at e-mai...  Col3

In [144]:
dfs[0]

,Sl.\nNo.,Title,Description in Simple Words\n(Please refer to applicable Policy Clause Number in\nnext column),Policy\nClause\nNumber
0,1.,Name of the Insurance\nProduct\nand Unique\nId...,LIC’s Jeevan Utsav\n(UIN: 512N363V02),Part A
1,2,Policy Number,_____________________,Part A
2,3,Type of Insurance\nPolicy,"Non-Par, Non-Linked, Individual, Savings, Whol...",Part B -\nDefinitions
3,4,Basic Policy details, Instalment Premium (Rs):\n__________\n(Taxes...,Schedule\nSchedule\nSchedule\nSchedule\nCondit...
4,5,"Riders opted, if any",<<Not Applicable (if rider is not opted)>>\n<<...,Schedule
5,6,Policy Coverage /\nbenefits payable, Benefit payable on Death:\nOn death of the L...,Condition\n1.A of Part\nC

In [155]:
def get_policy_clause(raw_clause):
    clauses = []
    for i, clause in enumerate(raw_clause):
        if raw_clause[i-1] == "Condition":
            clause = raw_clause[i-1] + " "+ clause
            clauses.remove(raw_clause[i-1])
        if len(clause) <= 3:
            clauses[-1] += " "+clause
            continue
        clauses.append(clause)
    return clauses

In [162]:
def get_section_details(clause_list, desc):
    details = ""
    for i, clause in enumerate(clauses):
        if clause is None or clause == "Schedule" or clause == "":
            continue
        if isinstance(desc, list):
            desc = desc[i]
        details += f"{desc}\n\nPolicy Clause Number: {clause}\n\n"
    return details

In [170]:
info = ""
for idx, row in dfs[0].iterrows():
    # info = ""
    details = ""
    
    desc = row.values[2]
    clauses = row.values[3].split('\n')

    if desc.find("\uf0b7") != -1:
        desc = desc.split("\uf0b7")[1:]
        
        clauses = get_policy_clause(clauses)
    details = get_section_details(clauses, desc)
    
    # else:
    #     continue
    info += f"## {row.values[1]}\n\n{details}"
print(info)

## Name of the Insurance
Product
and Unique
Identification Number
(UIN)

LIC’s Jeevan Utsav
(UIN: 512N363V02)

Policy Clause Number: Part A

## Policy Number

_____________________

Policy Clause Number: Part A

## Type of Insurance
Policy

Non-Par, Non-Linked, Individual, Savings, Whole
Life Insurance Plan

Policy Clause Number: Part B -

Non-Par, Non-Linked, Individual, Savings, Whole
Life Insurance Plan

Policy Clause Number: Definitions

## Basic Policy details

 Sum Assured on Death: Sum Assured on
Death is defined as Higher of Basic Sum
Assured or 7 times of Annualized Premium

Policy Clause Number: Condition 1.A of Part C

## Riders opted, if any

## Policy Coverage /
benefits payable

 Benefit payable on Death:
On death of the Life Assured after the date of
commencement of risk, Death Benefit equal to
“Sum Assured on Death” along with accrued
Guaranteed Additions shall be payable,

Policy Clause Number: Condition 1.A of Part C

In [165]:
info= ""

In [121]:
info

''

In [45]:
p = dfs[0][3:4].iloc[:, 2].values[0]
p

'\uf0b7 Instalment Premium (Rs):\n__________\n(Taxes, if any, as applicable from time to time\nare charged extra).\n\uf0b7 Mode of premium payment:\n_______\n\uf0b7 Premium Payment Term:\n_________\n\uf0b7 Basic Sum Assured (Rs):\n__________\n\uf0b7 Sum Assured on Death: Sum Assured on\nDeath is defined as Higher of Basic Sum\nAssured or 7 times of Annualized Premium'

In [44]:
clauses

['Schedule', 'Schedule', 'Schedule', 'Schedule', 'Condition', '1.A of PartC']

In [46]:
ts = []

In [114]:
def get_t(desc, i, l):
    skip = 0
    start, end = 0, 0
    temp = desc
    for idx in range(l):
        if skip < idx:
            start = temp.find("\uf0b7")
            temp = temp[start + 1:]
            print(start)
            skip += 1
            # start += 1
            continue
        # print(f"This is i: {i}")
        end = temp.find("\uf0b7") if idx < l - 1 else None
        print(f"end inside: {end}")
    # print(f"Desc: {desc}")
    # print()
    print(f"Start: {start}; End: {end}")
    return desc[start: end]

In [ ]:
# contents = ""

In [40]:
# for i, df in enumerate(dfs):
#     for idx, row in df.iterrows():
#         if idx < 3:
#             continue
#         print(row.values)
#         # title = row.values[1]
#         # desc = row.values[2]
#         # clause = row.values[3]
#         # txt = f"## {title} \n\n{desc} Policy Clause: {clause}"
#         # contents += txt
#         # contents += "\n\n"
#         if i == 0:
#             break

In [24]:
dfs[0]

,Sl.\nNo.,Title,Description in Simple Words\n(Please refer to applicable Policy Clause Number in\nnext column),Policy\nClause\nNumber
0,1.,Name of the Insurance\nProduct\nand Unique\nId...,LIC’s Jeevan Utsav\n(UIN: 512N363V02),Part A
1,2,Policy Number,_____________________,Part A
2,3,Type of Insurance\nPolicy,"Non-Par, Non-Linked, Individual, Savings, Whol...",Part B -\nDefinitions
3,4,Basic Policy details, Instalment Premium (Rs):\n__________\n(Taxes...,Schedule\nSchedule\nSchedule\nSchedule\nCondit...
4,5,"Riders opted, if any",<<Not Applicable (if rider is not opted)>>\n<<...,Schedule
5,6,Policy Coverage /\nbenefits payable, Benefit payable on Death:\nOn death of the L...,Condition\n1.A of Part\nC

In [32]:
vals = dfs[0][3:].iloc[:,2]
vals

3     Instalment Premium (Rs):\n__________\n(Taxes...
4    <<Not Applicable (if rider is not opted)>>\n<<...
5     Benefit payable on Death:\nOn death of the L...
Name: Description in Simple Words\n(Please refer to applicable Policy Clause Number in\nnext column), dtype: str

In [43]:
s = "abcbbc"