In [1]:
import pymupdf
import pandas as pd

In [8]:
sf = "lic’s_bima_kavach_cis.pdf"

In [9]:
dfs = []
pages = pymupdf.open(sf)

for page in pages:
    tables = page.find_tables()
    for table in tables:
        df = table.to_pandas()
        dfs.append(df)

In [10]:
len(dfs)

11

In [12]:
dfs[9]

,S\nNo,Description of Item of\nService,TAT
0,1,Acknowledgement to\ncomplaint,Immediately
1,2,Action on Complaint\nand Intimation of\ndecisi...,14 days
2,3,"If complaint is NOT\nresolved, communicate\nth...",14 days\nfrom original\ndate of\nreceipt of\nc...

In [13]:
dfs[10]

Empty DataFrame
Columns: [Col0, Col1, contact details is given in Part A
(First page) of the Policy
Document.
Alternatively the details of
Ombudsman can be found on the
below link:
https://cioins.co.in
022-69038800/69038812, Col3]
Index: []

In [14]:
dfs[8]

,Col0,Col1," For updated details , we request\nyou to regularly visit our website\nwww.licindia.in",Col3
0,17.,Grievances\n/Complaints,S Description of Item of TAT\nNo Service\n1 Ac...,Part G

In [15]:
df8_trans = dfs[8].T.reset_index().T.reset_index(drop=True)
df8_trans

,0,1,2,3
0,Col0,Col1," For updated details , we request\nyou to reg...",Col3
1,17.,Grievances\n/Complaints,S Description of Item of TAT\nNo Service\n1 Ac...,Part G

In [16]:
df9_trans = dfs[9].T.reset_index().T.reset_index(drop=True)
df9_trans

,0,1,2
0,S\nNo,Description of Item of\nService,TAT
1,1,Acknowledgement to\ncomplaint,Immediately
2,2,Action on Complaint\nand Intimation of\ndecisi...,14 days
3,3,"If complaint is NOT\nresolved, communicate\nth...",14 days\nfrom original\ndate of\nreceipt of\nc...

In [17]:
df7_trans = dfs[7].T.reset_index().T.reset_index(drop=True)
df7_trans

,0,1,2
0,S\nNo,Description of Item of\nService,TAT
1,1,Post Policy service\nrequests concerning\nmist...,7 days
2,2,Free look cancellation and\nrefund from the da...,7 days
3,3,Change of Address (KYC\nnorms to be complied),7 days
4,4,"Registration / Change of\nNomination, Assignment",7 days
5,5,Alteration in original policy\nconditions (whe...,7 days
6,6,Policy Loan,7 days
7,7,Decision on Policy revival\nafter receipt of a...,7 days
8,8,Issue of Premium\nPayment certificates\n(PPC),7 days
9,9,Issue of Duplicate Policy,7 days
10,10,Premium due intimation,One\nmonth\nbefore\ndue\ndate
11,11,Surrender or Partial\nwithdrawal of Policy,7 days

In [19]:
dfs[7]

,S\nNo,Description of Item of\nService,TAT
0,1,Post Policy service\nrequests concerning\nmist...,7 days
1,2,Free look cancellation and\nrefund from the da...,7 days
2,3,Change of Address (KYC\nnorms to be complied),7 days
3,4,"Registration / Change of\nNomination, Assignment",7 days
4,5,Alteration in original policy\nconditions (whe...,7 days
5,6,Policy Loan,7 days
6,7,Decision on Policy revival\nafter receipt of a...,7 days
7,8,Issue of Premium\nPayment certificates\n(PPC),7 days
8,9,Issue of Duplicate Policy,7 days
9,10,Premium due intimation,One\nmonth\nbefore\ndue\ndate
10,11,Surrender or Partial\nwithdrawal of Policy,7 days

In [18]:
df6_trans = dfs[6].T.reset_index().T.reset_index(drop=True)
df6_trans

,0,1,2,3
0,16.,Policy Servicing, Turn Around Time (TAT):\nS Description of It...,Col3

In [23]:
dfs[9]

,S\nNo,Description of Item of\nService,TAT
0,1,Acknowledgement to\ncomplaint,Immediately
1,2,Action on Complaint\nand Intimation of\ndecisi...,14 days
2,3,"If complaint is NOT\nresolved, communicate\nth...",14 days\nfrom original\ndate of\nreceipt of\nc...